from django import forms

class BairroForm(forms.Form):
	# Aqui você busca todos os bairros disponíveis
	# Botei como exemplo alguns dados, o certo seria pegar no banco
	# O primeiro element é o "ID" e o segundo é a label
	todos_bairros = (
				('1', 'CAPAO REDONDO'),
('2', 'CHACARA SANTA MARIA'),
('3', 'CIDADE AUXILIADORA'),
('4', 'CONJUNTO HABITACIONAL INSTITUTO ADVENTISTA'),
('5', 'CONJUNTO HABITACIONAL JARDIM SAO BENTO'),
('6', 'CONJUNTO HABITACIONAL PARQUE VALO VELHO'),
('7', 'JARDIM AMALIA'),
('8', 'JARDIM ANGELA'),
('9', 'JARDIM AURELIO'),
('10', 'JARDIM CAPAO REDONDO'),
('11', 'JARDIM CLARICE'),
('12', 'JARDIM COMERCIAL'),
('13', 'JARDIM DAS PALMEIRAS'),
('14', 'JARDIM DAS ROSAS'),
('15', 'JARDIM DO COLEGIO'),
('16', 'JARDIM DOM JOSE'),
('17', 'JARDIM ELEDY'),
('18', 'JARDIM FRATERNIDADE'),
('19', 'JARDIM GUARUJA'),
('20', 'JARDIM IAE'),
('21', 'JARDIM IMBE'),
('22', 'JARDIM IRACEMA'),
('23', 'JARDIM IRAPIRANGA'),
('24', 'JARDIM IRENE'),
('25', 'JARDIM ITAOCA'),
('26', 'JARDIM LEME'),
('27', 'JARDIM LILAH'),
('28', 'JARDIM MACEDONIA'),
('29', 'JARDIM MARACA'),
('30', 'JARDIM MARIA SAMPAIO'),
('31', 'JARDIM MARIANE'),
('32', 'JARDIM MITSUTANI'),
('33', 'JARDIM MODELO'),
('34', 'JARDIM PERI'),
('35', 'JARDIM RANIELE'),
('36', 'JARDIM REGINA'),
('37', 'JARDIM ROSANA'),
('38', 'JARDIM SAO BENTO'),
('39', 'JARDIM SAO BENTO NOVO'),
('40', 'JARDIM SAO JOSE'),
('41', 'JARDIM SAO MANOEL'),
('42', 'JARDIM SONIA INGA'),
('43', 'JARDIM SORAIA'),
('44', 'JARDIM VISTA LINDA'),
('45', 'MORRO DO INDIO'),
('46', 'PARQUE DO LAGO'),
('47', 'PARQUE FERNANDA'),
('48', 'PARQUE INDEPENDENCIA'),
('49', 'PARQUE LIGIA'),
('50', 'PARQUE NOVO SANTO AMARO'),
('51', 'PARQUE SONIA'),
('52', 'PIRAJUSSARA'),
('53', 'VALO VELHO'),
('54', 'VILA ANDRADE'),
('55', 'VILA DAS BELEZAS'),
('56', 'VILA FAZZEONI'),
('57', 'VILA NARCISO'),
('58', 'VILA REMO'),
				)
	# E você fala pro formulário que tem um campo bairros que aceita qualquer um dos bairros acima
	bairro = forms.ChoiceField(label='Bairro', choices=todos_bairros)
